version: "3"

services: 
  app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: leopard
    ports:
      - "8999:80"
    volumes:
      - .:/var/www/html
    command: >
      sh -c "service apache2 start && redis-server --protected-mode no"